development:
  adapter: postgresql
  encoding: unicode
  database: store_manager_rails_dev
  pool: 5
  username: Jay
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: store_manager_rails_test
  pool: 5
  username: Jay
  password:
